### ISSUE TITLE
Define the structure of the project in GitHub

### ISSUE THREAD

**Issue by SoreGums** [adivixproject/adivix-server#18]
Need to sort out the exact repos required and what will be in them.

I'll propose a structure and why I came up with this and in this issue we can go back and forth until we have something we like.

The end goal is for the everything under "github.com/adivixproject" to have a purpose and be defined so that as developers or contributors come and go everyone is singing from the same song sheet.

_first draft of this will be ready by http://goo.gl/gejpEL_

**Comment by SoreGums** [comment]
here is my first run down on this: https://github.com/adivixproject/adivix/wiki/Project-Structure:-Information-for-contributing

let chat in IRC about it this week.

will update again by http://goo.gl/4IhK1g

**Comment by SoreGums** [comment]
Nothing else to add at this time.

Noticed a few new repos made that aren't in the doc - perhaps the doc needs to be updated?

Will close this issue shortly then...

**Comment by SoreGums** [comment]
starting to wonder if we need this document to tell everyone how things work here - cause it doesn't seem to apply...

there are THREE repos in this project that aren't even in this document.

**Comment by adivixproject** [comment]
The three repos exist of the three different parts I am not sure how best to approach that so just created three different ones for each part. One I had to leave one for Panel documents.

**Comment by SoreGums** [comment]
my mind is boggled...

"...I am not sure how best to approach that..."

The title of the document is "Project Structure: Information for contributing" and in this document is "where things go" - that is how you approach it...

Maybe you have not actually clicked on this link yet

https://github.com/adivixproject/adivix/wiki/Project-Structure:-Information-for-contributing

 - let me know :D

**Comment by SoreGums** [comment]
closed cause this the adivix-server repo

**Comment by SoreGums** [comment]
There was a flare from beyond - labels are back and issue reopened

Document has been edited - after IRC discussions adivix.org website and "distributable code" doesn't fit in a central repo.

Things to be figured out though:
* is the a central "adivix" github repo needed as per is currently written?
* adivix has been renamed to adivix-server - this needs to be sorted out with the above

**Comment by SoreGums** [comment]
closing , follow along in #21
